version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "6001:5432"

volumes:
  postgres:
    driver: local
